Errors_Logs_And_Debugging Rnw to Rmd
Bioconductor/BiocParallel pull request #221
Opened 2022-09-14 14:47 UTC by villafup

@Bioconductor/sweave2rmd Initial conversion for review

2022-12-11 07:16 UTC, jwokaty requested changes
Hi @villafup, we just need a few changes before this is ready for the maintainers to review. Please do the following:

- [ ] Remove `.Rnw`
- [ ] Modify the author section in the `.Rmd` to include yourself as a contributor (as done in other `.Rmd` files
- [ ] Modify the `DESCRIPTION` to add yourself as a contributor
- [ ] Replace links to packages with calls to the `BiocStyle` function that writes the canonical links.

2022-12-15 19:03 UTC, villafup commented on vignettes/Errors_Logs_And_Debugging.Rmd
> +This vignette is part of the package [*BiocParallel*](http://bioconductor.org/packages/BiocParallel) and focuses on error handling and
`r CRANpkg('parallel')` gives me a 404.  By extension, for those marked as R commands (e.g., `\Rcode{MulticoreParam} ` do you think we should convert them as well (`'r MulticoreParam'`).  I've had problems with knitting with these in the past, especially when we try to run these commands with no parameters.

2022-12-15 19:40 UTC, mtmorgan commented on vignettes/Errors_Logs_And_Debugging.Rmd
> +This vignette is part of the package [*BiocParallel*](http://bioconductor.org/packages/BiocParallel) and focuses on error handling and
~~~
\Rcode{MulticoreParam}
~~~

should be translated as (no `r`)

~~~
`MulticoreParam`
~~~

~~~
`r CRANpkg('parallel')`
~~~
is actually a mistake in the vignette -- 'parallel' is a core package distributed by R, not a contributed package distributed by CRAN. Maybe just indicate the parallel package (with `**parallel**`??) without a hyperlink.

2023-07-09 21:36 UTC, villafup commented
- [ ] the `.Rmd` file knits to `HTML`
- [ ] `R CMD build` runs without errors or timeouts
- [ ] the tarball from `R CMD build` contains the `HTML` (check with the
  following by substituting the package name and vignette name `tar ztf
  package_name.tar.gz | grep 'doc/vignette_name'`)
- [ ] the `.Rnw` file has been removed
- In the `DESCRIPTION` file
  - [ ] `BiocStyle` and `knitr` are listed in `Suggests`
  - [ ] the line `VignetteBuilder: knitr` exists
  - [ ] any added lines use the same spacing and indents as the existing document
- If agreed with the Maintainer
  - [ ] the contributor is in the author list in the `DESCRIPTION` file*.
  - [ ] the contributor is in the author list in the vignette's YAML*.
- If this pull request involves converting from separate `Author` and  `Maintainer`
  lines to the `Authors@R` vector, please ensure that
  - [ ] the `Authors@R` vector includes the maintainer as specified with `role='cre'`.
  - [ ] the `Maintainer` line is completely removed.
- [ ] `HTML` document is representative of the `PDF` in content and
  in general the presentation
- [ ] Where the contributor was not able to preserve the content and presentation
  of the `PDF` is noted as a comment in the pull request
- [ ] the R Markdown file is representative of the Sweave document and follows
  best practices, such as replacing links to Bioconductor packages with calls
  to BiocStyle's `Biocpkg()`
- [ ] Only files necessary for the conversion are included in the pull request.
- [ ] Long lines have been broken up and reformatted, you can achieve this by
  selecting the text in your script and then clicking on `Code > Reflow Comment`
  in R Studio.
- [ ] Code blocks are surrounded by a blank line, and there are no blank lines
  before the start or after the end of the code within the code block.

2025-05-20 19:44 UTC, LiNk-NY commented
see #278

2025-05-20 19:44 UTC, closed without merging